-- MySQL Script generated by MySQL Workbench
-- 10/30/17 16:49:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blue_leaf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blue_leaf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blue_leaf` DEFAULT CHARACTER SET utf8 ;
USE `blue_leaf` ;

-- -----------------------------------------------------
-- Table `blue_leaf`.`ProductBrandTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_leaf`.`ProductBrandTable` (
  `brandID` INT(32) NOT NULL,
  `brandName` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`brandID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blue_leaf`.`ProductCategoryTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_leaf`.`ProductCategoryTable` (
  `categoryID` INT(32) NOT NULL,
  `categoryName` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`categoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blue_leaf`.`ProductTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_leaf`.`ProductTable` (
  `productID` INT(128) NOT NULL,
  `productName` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `imageURL` VARCHAR(255) NULL,
  `rating` INT(8) NULL,
  `certification` INT(4) NULL DEFAULT NULL,
  `brand_brandID` INT(32) NOT NULL,
  `category_categoryID` INT(32) NOT NULL,
  PRIMARY KEY (`productID`),
  INDEX `fk_product_brand1_idx` (`brand_brandID` ASC),
  INDEX `fk_product_category1_idx` (`category_categoryID` ASC),
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`brand_brandID`)
    REFERENCES `blue_leaf`.`ProductBrandTable` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_categoryID`)
    REFERENCES `blue_leaf`.`ProductCategoryTable` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blue_leaf`.`UserTypeTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_leaf`.`UserTypeTable` (
  `userType` INT(2) NOT NULL,
  `Role` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`userType`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blue_leaf`.`UserInfoTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_leaf`.`UserInfoTable` (
  `userID` INT(32) NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(64) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `userType` INT(2) NOT NULL,
  PRIMARY KEY (`userID`),
  INDEX `fk_user_type_idx` (`userType` ASC),
  CONSTRAINT `fk_user_type`
    FOREIGN KEY (`userType`)
    REFERENCES `blue_leaf`.`UserTypeTable` (`userType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blue_leaf`.`UserRegistryTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_leaf`.`UserRegistryTable` (
  `registryID` INT(32) NOT NULL AUTO_INCREMENT,
  `registryType` INT(4) NOT NULL,
  `userID` INT(32) NOT NULL,
  PRIMARY KEY (`registryID`, `userID`),
  INDEX `fk_registry_user1_idx` (`userID` ASC),
  CONSTRAINT `fk_registry_user1`
    FOREIGN KEY (`userID`)
    REFERENCES `blue_leaf`.`UserInfoTable` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blue_leaf`.`RegistryProductTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_leaf`.`RegistryProductTable` (
  `registryID` INT(32) NOT NULL,
  `productID` INT(128) NOT NULL,
  PRIMARY KEY (`registryID`, `productID`),
  INDEX `ProductId_idx` (`productID` ASC),
  CONSTRAINT `registryID`
    FOREIGN KEY (`registryID`)
    REFERENCES `blue_leaf`.`UserRegistryTable` (`registryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `productID`
    FOREIGN KEY (`productID`)
    REFERENCES `blue_leaf`.`ProductTable` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blue_leaf`.`BuyerUserTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_leaf`.`BuyerUserTable` (
  `registryID` INT(32) NOT NULL,
  `productID` INT(128) NULL DEFAULT NULL,
  `BuyerUserID` INT(32) NOT NULL,
  PRIMARY KEY (`BuyerUserID`, `registryID`),
  INDEX `ProductID_idx` (`productID` ASC),
  INDEX `registryID_idx` (`registryID` ASC),
  CONSTRAINT `ProductID`
    FOREIGN KEY (`productID`)
    REFERENCES `blue_leaf`.`ProductTable` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BuyerUserID`
    FOREIGN KEY (`BuyerUserID`)
    REFERENCES `blue_leaf`.`UserInfoTable` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `registryID`
    FOREIGN KEY (`registryID`)
    REFERENCES `blue_leaf`.`UserRegistryTable` (`registryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blue_leaf`.`PrivateRegistryMappingTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_leaf`.`PrivateRegistryMappingTable` (
  `userID` INT(64) NOT NULL,
  `registryID` INT(32) NULL DEFAULT NULL,
  `BuyerUserID` INT(32) NOT NULL,
  PRIMARY KEY (`userID`, `BuyerUserID`),
  INDEX `buyerUserID_idx` (`BuyerUserID` ASC),
  INDEX `registryID_idx` (`registryID` ASC),
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `blue_leaf`.`UserInfoTable` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BuyerUserID`
    FOREIGN KEY (`BuyerUserID`)
    REFERENCES `blue_leaf`.`UserInfoTable` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `registryID`
    FOREIGN KEY (`registryID`)
    REFERENCES `blue_leaf`.`UserRegistryTable` (`registryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blue_leaf`.`registry_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_leaf`.`registry_product` (
  `registry_userID` INT(32) NOT NULL,
  `registry_userType` INT(2) NOT NULL,
  `product_itemID` INT(128) NOT NULL,
  PRIMARY KEY (`registry_userID`, `registry_userType`, `product_itemID`),
  INDEX `fk_registry_has_product_product1_idx` (`product_itemID` ASC),
  INDEX `fk_registry_has_product_registry1_idx` (`registry_userID` ASC, `registry_userType` ASC),
  CONSTRAINT `fk_registry_has_product_registry1`
    FOREIGN KEY (`registry_userID`)
    REFERENCES `blue_leaf`.`UserRegistryTable` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registry_has_product_product1`
    FOREIGN KEY (`product_itemID`)
    REFERENCES `blue_leaf`.`ProductTable` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
