-- MySQL Script generated by MySQL Workbench
-- 11/02/17 23:05:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blueleaf-323357c1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blueleaf-323357c1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blueleaf-323357c1` DEFAULT CHARACTER SET utf8 ;
USE `blueleaf-323357c1` ;

-- -----------------------------------------------------
-- Table `blueleaf-323357c1`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueleaf-323357c1`.`brand` (
  `brandID` INT(32) NOT NULL,
  `brandName` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`brandID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blueleaf-323357c1`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueleaf-323357c1`.`category` (
  `categoryID` INT(32) NOT NULL,
  `categoryName` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`categoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blueleaf-323357c1`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueleaf-323357c1`.`product` (
  `itemID` INT(128) NOT NULL,
  `itemName` VARCHAR(45) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `image` VARCHAR(256) NULL DEFAULT NULL,
  `rating` INT(8) NULL DEFAULT NULL,
  `certification` INT(4) NULL DEFAULT NULL,
  `brand_brandID` INT(32) NOT NULL,
  `category_categoryID` INT(32) NOT NULL,
  PRIMARY KEY (`itemID`, `brand_brandID`, `category_categoryID`),
  INDEX `fk_product_brand1_idx` (`brand_brandID` ASC),
  INDEX `fk_product_category1_idx` (`category_categoryID` ASC),
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`brand_brandID`)
    REFERENCES `blueleaf-323357c1`.`brand` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_categoryID`)
    REFERENCES `blueleaf-323357c1`.`category` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blueleaf-323357c1`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueleaf-323357c1`.`type` (
  `userType` INT(2) NOT NULL,
  `Role` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`userType`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blueleaf-323357c1`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueleaf-323357c1`.`user` (
  `userID` INT(32) NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(64) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `userType` INT(2) NOT NULL,
  PRIMARY KEY (`userID`, `userType`),
  INDEX `fk_user_type_idx` (`userType` ASC),
  CONSTRAINT `fk_user_type`
    FOREIGN KEY (`userType`)
    REFERENCES `blueleaf-323357c1`.`type` (`userType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blueleaf-323357c1`.`registrylist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueleaf-323357c1`.`registrylist` (
  `registryID` INT(32) NOT NULL,
  `itemID` INT(128) NULL DEFAULT NULL,
  PRIMARY KEY (`registryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blueleaf-323357c1`.`registry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueleaf-323357c1`.`registry` (
  `registryID` INT(32) NULL DEFAULT NULL,
  `registryType` INT(4) NULL DEFAULT NULL,
  `userID` INT(32) NOT NULL,
  `userType` INT(2) NOT NULL,
  `registrylist_registryID` INT(32) NOT NULL,
  PRIMARY KEY (`userID`, `userType`, `registrylist_registryID`),
  INDEX `fk_registry_user1_idx` (`userID` ASC, `userType` ASC),
  INDEX `fk_registry_registrylist1_idx` (`registrylist_registryID` ASC),
  CONSTRAINT `fk_registry_user1`
    FOREIGN KEY (`userID` , `userType`)
    REFERENCES `blueleaf-323357c1`.`user` (`userID` , `userType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registry_registrylist1`
    FOREIGN KEY (`registrylist_registryID`)
    REFERENCES `blueleaf-323357c1`.`registrylist` (`registryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blueleaf-323357c1`.`sendgift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueleaf-323357c1`.`sendgift` (
  `registryID` INT(32) NULL DEFAULT NULL,
  `itemID` INT(128) NULL DEFAULT NULL,
  `user_userID` INT(32) NOT NULL,
  `user_userType` INT(2) NOT NULL,
  PRIMARY KEY (`user_userID`, `user_userType`),
  INDEX `fk_sendgift_user1_idx` (`user_userID` ASC, `user_userType` ASC),
  CONSTRAINT `fk_sendgift_user1`
    FOREIGN KEY (`user_userID` , `user_userType`)
    REFERENCES `blueleaf-323357c1`.`user` (`userID` , `userType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blueleaf-323357c1`.`toshare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueleaf-323357c1`.`toshare` (
  `userID` INT(64) NOT NULL,
  `registryID` INT(32) NULL DEFAULT NULL,
  `userName` INT(64) NULL DEFAULT NULL COMMENT 'Share to this user',
  `user_userID` INT(32) NOT NULL,
  `user_userType` INT(2) NOT NULL,
  PRIMARY KEY (`userID`, `user_userID`, `user_userType`),
  INDEX `fk_toshare_user1_idx` (`user_userID` ASC, `user_userType` ASC),
  CONSTRAINT `fk_toshare_user1`
    FOREIGN KEY (`user_userID` , `user_userType`)
    REFERENCES `blueleaf-323357c1`.`user` (`userID` , `userType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blueleaf-323357c1`.`registry_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueleaf-323357c1`.`registry_product` (
  `registry_userID` INT(32) NOT NULL,
  `registry_userType` INT(2) NOT NULL,
  `product_itemID` INT(128) NOT NULL,
  PRIMARY KEY (`registry_userID`, `registry_userType`, `product_itemID`),
  INDEX `fk_registry_has_product_product1_idx` (`product_itemID` ASC),
  INDEX `fk_registry_has_product_registry1_idx` (`registry_userID` ASC, `registry_userType` ASC),
  CONSTRAINT `fk_registry_has_product_registry1`
    FOREIGN KEY (`registry_userID` , `registry_userType`)
    REFERENCES `blueleaf-323357c1`.`registry` (`userID` , `userType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registry_has_product_product1`
    FOREIGN KEY (`product_itemID`)
    REFERENCES `blueleaf-323357c1`.`product` (`itemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
